terraform {
  # NOTE: Plan specifies >= 1.9, but adjusted to >= 1.8 for compatibility with local environment
  # Upgrade to Terraform 1.9+ recommended for production use
  required_version = ">= 1.8"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }

    azapi = {
      source  = "Azure/azapi"
      version = "~> 2.0"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }

    acme = {
      source  = "vancluever/acme"
      version = "~> 2.43"
    }

    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }

  # Backend configuration will be auto-generated by Terragrunt
  backend "azurerm" {}
}
